// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ProjectThesis.ViewModels;

namespace ProjectThesis.Migrations
{
    [DbContext(typeof(ThesisDbContext))]
    partial class ThesisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("ProjectThesis.Models.Faculty", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("FacultyId");

                    b.ToTable("Faculty");
                });

            modelBuilder.Entity("ProjectThesis.Models.FieldOfStudy", b =>
                {
                    b.Property<int>("FieldOfStudyId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("FieldOfStudyId");

                    b.ToTable("FieldOfStudy");
                });

            modelBuilder.Entity("ProjectThesis.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DegreeCycle");

                    b.Property<int>("FacultyId");

                    b.Property<int>("StudentNo");

                    b.Property<int>("SupId");

                    b.Property<int>("UserId");

                    b.HasKey("StudentId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("SupId");

                    b.HasIndex("UserId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ProjectThesis.Models.Supervisor", b =>
                {
                    b.Property<int>("SupervisorId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FacId");

                    b.Property<int>("StudentLimit");

                    b.Property<int>("UserId");

                    b.HasKey("SupervisorId");

                    b.HasIndex("FacId");

                    b.HasIndex("UserId");

                    b.ToTable("Supervisors");
                });

            modelBuilder.Entity("ProjectThesis.Models.Thesis", b =>
                {
                    b.Property<int>("ThesisId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DegreeCycle");

                    b.Property<int>("FosId");

                    b.Property<int>("StudentId");

                    b.Property<string>("Subject");

                    b.Property<int>("SupId");

                    b.HasKey("ThesisId");

                    b.HasIndex("FosId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("SupId");

                    b.ToTable("Thesis");
                });

            modelBuilder.Entity("ProjectThesis.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ProjectThesis.Models.Student", b =>
                {
                    b.HasOne("ProjectThesis.Models.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProjectThesis.Models.Supervisor", "Sup")
                        .WithMany("Students")
                        .HasForeignKey("SupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProjectThesis.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProjectThesis.Models.Supervisor", b =>
                {
                    b.HasOne("ProjectThesis.Models.Faculty", "Fac")
                        .WithMany()
                        .HasForeignKey("FacId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProjectThesis.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ProjectThesis.Models.Thesis", b =>
                {
                    b.HasOne("ProjectThesis.Models.FieldOfStudy", "Fos")
                        .WithMany()
                        .HasForeignKey("FosId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProjectThesis.Models.Student", "Student")
                        .WithOne("ChosenThesis")
                        .HasForeignKey("ProjectThesis.Models.Thesis", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProjectThesis.Models.Supervisor", "Sup")
                        .WithMany("Theses")
                        .HasForeignKey("SupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
